package.json
src/boot/boot.js
src/cachier/index.js
src/test/cachier/cachier_spec.js
tasks/support/test-runner/index.js

Fix build errors on Travis CI

---

gulpfile.js
package.json
src/polyfill/index.js
tasks/support/jscs.js

Bluebird seems to be more well-maintained and more widely used.

use bluebird instead of prfun

---

spec/game/game-input_spec.js
src/game/game-controller.js
src/game/input/control.js
src/game/input/index.js
tasks/lint.js

Only with hardcoded keyboard scheme.
Have to work around jshint bug... jshint/jshint/issues/2138

Initial GameInput implementation (Closes #100)

---

config/webpack.js
package.json
src/boot/error-dialog.js
src/boot/index.js
src/webpack-istanbul-babel-skipper/index.js

This should make the coverage more accurate

chore(isparta): use Isparta for coverage instrumentation

---

spec/game/audio/player-audio_spec.js
spec/game/audio/wave-factory_spec.js
spec/game/loaders/samples-loader_spec.js
spec/game/notechart_spec.js
spec/sampling-master/sampling-master_spec.js
src/game/audio/index.js
src/game/audio/player-audio.js
src/game/audio/wave-factory.js
src/game/game-controller.js
src/game/game.js
src/game/index.js
src/game/loaders/game-loader.js
src/game/loaders/samples-loader.js
src/game/notechart.js
src/sampling-master/index.js
src/test/load.js

Implement GameAudio

---

public/skins/default/_lib/common.jade
public/skins/default/skin_data.yml
public/skins/default/skin_screen.xml
public/skins/default/skin_template.jade
public/skins/default/skin_touch.xml
spec/game/display/player-display_spec.js
spec/game/notechart_spec.js
spec/game/spec_helper.js
spec/game/state/player-state_spec.js
spec/scintillator/fixtures/expr_object.xml
spec/scintillator/fixtures/expr_object_var.xml
spec/scintillator/fixtures/expr_variables.xml
spec/scintillator/fixtures/invalid_no_image.xml
spec/scintillator/fixtures/sprite_attrs.xml
spec/scintillator/fixtures/sprite_invalid_blend.xml
spec/scintillator/scintillator_spec.js
src/game/audio/index.js
src/game/display/player-display.js
src/game/game-controller.js
src/game/game-timer.js
src/game/judgments.js
src/game/notechart.js
src/game/state/player-state.js
src/game/state/player-stats.js
src/scintillator/loader.js

Perform judgment on notes

---

spec/game/display/player-display_spec.js
spec/game/state/player-state_spec.js
src/game/display/player-display.js
src/game/judgments.js
src/game/state/player-state.js

feat(PlayerState): judge long notes on and off

---

package.json
public/sw-loader.js
src/app/game-launcher.js
src/app/index.js
src/app/service-worker.js
src/app/ui/service-worker-registration-scene.jsx
src/app/ui/service-worker-registration-scene.scss
src/hacks/service-worker-url/index.loader.js
src/ui/fonts.scss

So that this game can be played offline wow

Use Service Worker to allow offline mode

---

config/webpack.js
package.json
src/app/stores/music-select-store.js
src/app/ui/MusicInfoTabStats.jsx
src/app/ui/MusicInfoTabStats.scss
src/app/ui/MusicListItem.jsx
src/app/ui/MusicListItemChartContainer.jsx
src/app/ui/MusicSelectScene.jsx
src/app/ui/RankingTable.jsx
src/app/ui/withPersonalRecord.jsx
src/rules/accuracy.js
src/test/index.js
src/ui/fonts.scss

- Display “no songs” instead of an error message when filtering songs and it is not found.
- Show personal record in the stats tab in music selection screen
- Update sinon workaround

Moar stuffs

---

spec/game/audio/wave-factory_spec.js
spec/sampling-master/sampling-master_spec.js
src/app/game-launcher.js
src/game/audio/index.js
src/game/audio/player-audio.js
src/game/audio/wave-factory.js
src/sampling-master/index.js

ReplayGain

---

src/online/scoreboard-system/createScoreboardClient.js

We did not check if the reserved account has been linked or not. If not, it is for anyone to take.

Fix sign up bug

---

package.json
yarn.lock

Upgrade node-sass to prevent Windows build failure

---

bin/create-component
config/webpack.js
package.json
src/app/ui/AboutScene.jsx
src/app/ui/ChangelogPanel.jsx
src/app/ui/CustomBMS.jsx
src/app/ui/MusicChartSelector.jsx
src/app/ui/MusicChartSelectorItem.jsx
src/app/ui/MusicInfo.jsx
src/app/ui/MusicListItemChart.jsx
src/app/ui/MusicSelectScene.jsx
src/app/ui/OptionsButton.jsx
src/app/ui/OptionsInput.jsx
src/app/ui/Ranking.jsx
src/app/ui/RankingContainer.jsx
src/app/ui/RankingTable.jsx
src/app/ui/ResultGrade.jsx
src/app/ui/ResultTable.jsx
src/app/ui/TitleScene.jsx
src/ui/YouTube.jsx

Reference: #437.
**Work in progress. Do not merge.**
*Those little things, those little things...*
This includes most of the fixes suggested in the code review from #444. This PR will also contain numerous other code improvements before testing if all the plugins/codebase will work in React 16.
I've also fixed how the `webpack.DefinePlugin` is defined, in order to properly output [the production build of React](https://reactjs.org/docs/optimizing-performance.html#use-the-production-build).

Pre-React 16 optimisation work

---

src/music-collection/groupSongsIntoCategories.js
src/rules/accuracy.js

Since new songs are not updated as often, they will be put as new for 2 months.

New song threshold

---

public/includes/amplitude.inc
public/index.html
src/app/analytics.js

Amplitude is a very cool product analytics platform. Let’s try putting it on Bemuse so that I can gather insights from users more easily.

Analytics tracking with Amplitude

---

src/game/game-controller.js

This breaks the behavior for those who has set a latency value. Estimated to affect 5.4% of users.
Maybe I should add an option to make this behavior adjustable.

:bug: Fix bug where display time is not in sync with state [BREAKING]

---

README.md

Fixed images in readme

---

docs/developer-guide.md
docs/music-server.md
website/package.json
website/static/css/custom.css
yarn.lock

Include additional prerequisite check in Developer Guide.

Added more Windows information in docs

---

src/app/io/CustomSongsIO.js
src/resources/ipfs-resources.js

- IPFS companion is an extension
- But based on my testing, performance is not as good as using a public gateway
- Switch to use Cloudflare’s IPFS gateway

Support IPFS companion (behind feature flag) and switch to cloudflare-ipfs

---

tsconfig.lib.json

https://www.typescriptlang.org/docs/handbook/project-references.html

Mark all library projects as "composite"

---

src/game/display/game-display.scss
src/game/display/index.js

The TUTORIAL now displays a tooltip that teaches new players how to exit the game.

Tutorial exit tip

---

CHANGELOG.md
bin/strip-changelog-pre-version-postfix

Minor CHANGELOG update: Removed trailing .0.0 in version number.

Fix changelog trailing zeros

---

src/app/PreloadedCustomBMS.ts
src/app/game-launcher.ts
src/app/io/CustomSongsIO.js
src/app/query-flags.js
src/app/ui/CustomBMS.jsx
src/app/ui/MusicSelectScene.jsx
src/game/display/player-display.js
src/resources/custom-song-resources.ts
src/resources/dnd-resources.ts

Add support for `?archive` query flag ([requested](https://twitter.com/Nekokan_Server/status/1173186650865713153) by [@Nekokan])

Archive query flag support

---

docs/faq.md

Updated docs to add FAQ item about framerate issues when hardware acceleration is not turned on.

:memo: Add docs about hardware acceleration

---

packages/bemuse-tools/src/packer.js

Fix #624
Hakkyou kaiden BMS player from Taiwan, happy to be contributing to my favorite web-based rhythm game :)

Updates usage of `co` to async function in src/packer.js

---

src/devtools/playgrounds/skin.js

Updates usage of to async function in src/devtools/playgrounds/skin.js #628

---

packages/bemuse-notechart/src/index.ts
src/game/display/player-display.js

Move getKeyMode to bemuse-notechart

---

packages/bemuse-tools/src/bemuse-packer.js

Updates usage of `co` to async function in bemuse-packer.js

---

src/scene-manager/index.js

Updates usage of `co` to async function in scene-manager/index.js

---

.sonarcloud.properties

Make sure sonarcloud still checks for code quality in the game directory.

Updated sonarcloud properties to match new game directory

---

bemuse/src/app/game-launcher.ts
bemuse/src/app/query-flags.js

**Reduced sound volume by 4dB** to prevent sound distortion in Windows. If the game sounds quieter, please increase your sound volume.

Reduced sound volume by 4dB to prevent clipping in Windows

---

bemuse/tsconfig.json

Updated build tooling to generate more modern code for better performance and easier debugging.

Set compilation target to ES2019

---

bemuse/src/music-previewer/index.js
bemuse/src/sampling-master/index.js

Fix some bugs about catching an error from `Promise` with `try`-`catch` [reported by sonarcloud](https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=bemusic_bemuse).
Improved error handling code in audio handling code.

fix: Fix to catch error from Promise

---

.vscode/settings.json

https://github.com/microsoft/rushstack/issues/3457
Fixed high CPU usage when developing the project inside VS Code.

Fixed high CPU usage when developing the project inside VS Code

---

.github/actions/rush-cache/action.yml
.github/actions/setup-project/action.yml
.github/workflows/checks.yml
.github/workflows/ci.yml
.github/workflows/tidy.yml
common/autoinstallers/bemuse-linter/dangerfile.ts
packages/bms/package.json

Fixed #732
| | checks | ci | tidy |
| --- | --- | --- | --- |
| **Before** | 5m24s | 7m49s | 4m59s |
| **After (cold)** | 6m15s | 9m33s | 5m17s |
| **After (warm)** | 1m12s | 4m49s | 0m44s |
Improved build performance in GitHub Actions.

Refactor GitHub Actions workflows to use composite steps and add CI caching

---

bemuse/src/app/ui/MusicInfoTabStats.scss
bemuse/src/app/ui/OptionsCheckbox.scss
bemuse/src/online/parse/cloud-code/public/index.html

Fixed some bugs about HTML/CSS [as reported by sonarcloud](https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=bemusic_bemuse).
Fixed some bugs about HTML/CSS as [reported](https://sonarcloud.io/project/issues?issues=AW0WEOc5aLThNPGzLxnI&open=AW0WEOc5aLThNPGzLxnI&id=bemusic_bemuse) [by](https://sonarcloud.io/project/issues?issues=AW0WEOdcaLThNPGzLxnM&open=AW0WEOdcaLThNPGzLxnM&id=bemusic_bemuse) [sonarcloud](https://sonarcloud.io/project/issues?issues=AW0WEOg6aLThNPGzLxn1&open=AW0WEOg6aLThNPGzLxn1&id=bemusic_bemuse).

fix: Fix minor bugs in HTML/CSS

---

CODE_OF_CONDUCT.md
README.md

Updated community health files on the GitHub repository.

Added CODE_OF_CONDUCT.md and also updated README.md

---

.github/actions/semgrep/action.yml
.github/actions/semgrep/semgrep-problem-matcher.json
.github/workflows/ci.yml
.semgrep.yml
.vscode/tasks.json
bemuse/src/previewer/BarDot.tsx
bemuse/src/previewer/PreviewCanvas.tsx
bemuse/src/previewer/PreviewFileDropHandler.tsx
bemuse/src/previewer/PreviewInfo.tsx
bemuse/src/previewer/PreviewKeyHandler.tsx
bemuse/src/ui/Button.tsx
bemuse/src/ui/VBox.tsx
bemuse/types/react.d.ts

Added [Semgrep](https://semgrep.dev/) to our toolchain to further help us maintain consistent thoughout codebase.

Add Semgrep

---

bemuse/src/app/service-worker.js
e2e/playwright.config.ts
e2e/tests/gameplay.spec.ts
e2e/tests/project-site.spec.ts

Fixed a problem where the project documentation website cannot be accessed when a Service Worker is installed.

Fix problem where project site cannot be accessed once Service Worker is installed

---

bemuse/src/coming-soon/demo/index.js
bemuse/src/game/loaders/samples-loader.js
packages/bemuse-tools/src/server.js

Added support for `.flac` keysounds in custom songs. Note that this only works on browsers that natively support FLAC files.

Add support for FLAC keysounds

---

bemuse/src/app/index.tsx
bemuse/src/app/ui/MusicInfoTabStats.tsx
bemuse/src/app/ui/MusicListItemChart.tsx
bemuse/src/app/ui/Ranking.scss
bemuse/src/devtools/playgrounds/result.js
bemuse/src/online/scoreboard-system/createFakeScoreboardClient.ts
bemuse/src/rules/mapping-mode.ts
bemuse/src/scene-manager/index.tsx
e2e/tests/gameplay.spec.ts
e2e/tests/online-ranking.spec.ts

Add a bunch of more [black-box testing](https://youtu.be/vbIWSwz8NxQ) for the online ranking system.

Add more testing for online ranking
